#=
End-to-end multi-worker test for AzManagers.addprocs against a real Azure
subscription. Run manually from a workstation or a small "controller" VM
inside the worker VNet to verify that:

  - templates render correctly
  - a scale set is created
  - Julia workers register with the master
  - automatic ppi (procs-per-instance) placement
    (cpu_set / numa_node / socket / pinning_backend) matches the SKU you provisioned
  - optional MPI nested launch (ppi > 1 AND mpi_ranks_per_worker > 0)
  - the scale set is torn down at the end

Each scenario is gated by a [scenarios] flag (or its SCENARIOS_<NAME> env-var
override). Set only the ones you want to run.

================================================================================
PREREQUISITES (host running this script)
================================================================================

  - Julia 1.9 or newer (package extensions ship with 1.9+)
  - This repo cloned and activated: `julia --project=. test/multi_worker_test.jl`
  - AzSessions installed; AzManagers will be loaded from the project
  - Network access to https://management.azure.com and the worker subnet

================================================================================
AZURE RESOURCES YOU MUST HAVE
================================================================================

  1. An Azure subscription you can deploy to.
  2. A resource group in your chosen region.
  3. A VNet + subnet in that resource group. The workers will get NICs on this
     subnet, and the host running this script must be able to reach them on the
     Julia worker port (default ephemeral; see JULIA_WORKER_TIMEOUT).
  4. A Shared Image Gallery, image definition, and at least one image version
     containing:
       * Julia (matching the version flag in your `exename`)
       * AzManagers checked out and precompiled, OR `customenv=true` so the
         current project is shipped to the workers (slower bootstrap)
       * For MPI tests: an Open MPI build whose mpirun accepts
         `--cpu-set <cpu-list> --bind-to cpu-list:ordered`
       * `numactl` and `lscpu` (already present on most Ubuntu/RHEL images)
     If you don't have an image yet, the Packer file at test/image.pkr.hcl is a
     starting point.
  5. A service principal (client_id + client_secret + tenant) with Contributor
     on the resource group, OR a managed identity if you're running on Azure.

================================================================================
CONFIGURATION
================================================================================

Settings come from a TOML file (preferred) with optional env-var overrides.

Two ways to obtain a starting config:

  (a) Annotated template in this repo — fully commented, recommended:

         cp test/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
         chmod 600 ~/.azmanagers/multi_worker_test.toml

  (b) Minimal template generated by the script:

         julia --project=. test/multi_worker_test.jl --init

In both cases, edit ~/.azmanagers/multi_worker_test.toml to fill in the
REPLACE-ME placeholders with values from your Azure subscription, then run:

         julia --project=. test/multi_worker_test.jl
         julia --project=. test/multi_worker_test.jl path/to/other.toml

TOML schema (all fields required unless marked optional):

  [azure]
  subscription_id = "..."
  resource_group  = "..."
  tenant_id       = "..."
  client_id       = "..."
  client_secret   = "..."
  vnet            = "..."
  subnet          = "..."
  gallery         = "..."
  image_name      = "..."
  location        = "southcentralus"   # optional
  sku_name        = "Standard_D4s_v5"  # optional
  ssh_user        = "cvx"              # optional
  spot            = true                # optional, Azure Spot workers

  [scenarios]
  basic        = true     # ppi=1 smoke test (one worker, hostname check)
  placement    = true     # pinning matrix: probes topology then sweeps
                          # ppi = 1 / sockets / numa / 2*numa, asserting
                          # per worker that cpu_set/numa/socket match the
                          # planner and that kernel taskset affinity
                          # matches the recorded cpu_set
  mpi_nested   = false    # n=1, ppi=2, mpi_ranks_per_worker=2
  ppi          = 2        # procs-per-instance for mpi_nested only;
                          # the placement matrix derives its own ppi sweep
  mpi_ranks_per_worker = 2  # optional override for mpi_nested
  mpi_flags    = ""       # optional extra mpirun flags
  keep         = false    # skip rmprocs/rmgroup at the end

Any TOML setting can be overridden at the command line:

  AZURE_SUBSCRIPTION_ID=...  SCENARIOS_BASIC=1  julia --project=. test/multi_worker_test.jl

(env keys are upper-snake of section + field, joined with underscore).

================================================================================
RUN IT
================================================================================

The launcher machine (the one running this script) must be on a network with a
route to the worker subnet — Julia Distributed sets up a TCP listener on the
launcher and each worker dials back to it. In practice that means either a
small controller VM inside the same Azure VNet (recommended) or a VPN /
peering setup that drops your workstation onto that VNet. A home laptop
behind NAT cannot host the master.

  cd ~/.julia/dev/AzManagers
  cp test/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
  chmod 600 ~/.azmanagers/multi_worker_test.toml
  $EDITOR ~/.azmanagers/multi_worker_test.toml
  julia --project=. test/multi_worker_test.jl

You'll see logs like:

  [ Info: writing templates for sku=Standard_HB176rs_v4
  [ Info: addprocs placement: group=mwt-place-abcd ...
  [ Info: worker 2: cpu_set=0-87 numa_node=0 socket=0 pinning_backend=numactl
  [ Info: worker 3: cpu_set=88-175 numa_node=1 socket=0 pinning_backend=numactl
  [ Info: taskset for pid 2 expected=0-87 got=pid 12345's current affinity list: 0-87
  [ Info: teardown complete for scale set mwt-place-abcd

================================================================================
HOW TO CLEAN UP IF SOMETHING WEDGES
================================================================================

  az vmss list -g $RESOURCE_GROUP --query "[?starts_with(name,'mwt')].name" -o tsv \
      | xargs -I {} az vmss delete -g $RESOURCE_GROUP -n {}

=#

using Distributed, AzManagers, AzSessions, Random, Test, HTTP, JSON, TOML

const TEMPLATE_NAME       = "mwt" * randstring('a':'z',8)
const DEFAULT_CONFIG_PATH = joinpath(homedir(), ".azmanagers", "multi_worker_test.toml")

const TEMPLATE_TOML = """
[azure]
subscription_id = "REPLACE-ME"
resource_group  = "REPLACE-ME"
tenant_id       = "REPLACE-ME"
client_id       = "REPLACE-ME"
client_secret   = "REPLACE-ME"
vnet            = "REPLACE-ME"
subnet          = "REPLACE-ME"
gallery         = "REPLACE-ME"
image_name      = "REPLACE-ME"
location        = "southcentralus"
sku_name        = "Standard_D4s_v5"
ssh_user        = "cvx"
spot            = true

[scenarios]
basic                 = true
placement             = false
mpi_nested            = false
ppi                   = 2
mpi_ranks_per_worker  = 2
mpi_flags             = ""
keep                  = false
"""

function init_config(path)
    if isfile(path)
        @info "config already exists at $path; not overwriting"
        return
    end
    mkpath(dirname(path))
    write(path, TEMPLATE_TOML)
    try
        chmod(path, 0o600)
    catch
    end
    @info "wrote template config to $path; edit it and rerun"
end

function load_config(path)
    isfile(path) ||
        error("config file $path does not exist; run with --init to create a template")
    TOML.parsefile(path)
end

function get_field(cfg, section, field; default = nothing, required = true)
    env_key = uppercase(string(section, "_", field))
    if haskey(ENV, env_key)
        return ENV[env_key]
    end
    section_table = get(cfg, string(section), Dict())
    if haskey(section_table, string(field))
        return section_table[string(field)]
    end
    default !== nothing && return default
    required && error("missing config field [$section].$field (or env var $env_key)")
    nothing
end

function get_bool(cfg, section, field; default = false)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Bool && return value
    value isa AbstractString && return lowercase(value) in ("1", "true", "yes")
    Bool(value)
end

function get_int(cfg, section, field; default)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Integer && return Int(value)
    parse(Int, string(value))
end

function build_test_templates(cfg)
    subscriptionid = get_field(cfg, :azure, :subscription_id)
    resourcegroup  = get_field(cfg, :azure, :resource_group)
    tenant_id      = get_field(cfg, :azure, :tenant_id)
    client_id      = get_field(cfg, :azure, :client_id)
    client_secret  = get_field(cfg, :azure, :client_secret)
    vnet           = get_field(cfg, :azure, :vnet)
    subnet         = get_field(cfg, :azure, :subnet)
    gallery        = get_field(cfg, :azure, :gallery)
    imagename      = get_field(cfg, :azure, :image_name)
    location       = get_field(cfg, :azure, :location; default = "southcentralus", required = false)
    sku            = get_field(cfg, :azure, :sku_name; default = "Standard_D4s_v5", required = false)
    ssh_user       = get_field(cfg, :azure, :ssh_user; default = "cvx", required = false)

    @info "writing templates for sku=$sku location=$location"

    sstemplate = AzManagers.build_sstemplate(
        TEMPLATE_NAME;
        subscriptionid     = subscriptionid,
        admin_username     = ssh_user,
        location           = location,
        resourcegroup      = resourcegroup,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet,
        imagegallery       = gallery,
        imagename          = imagename,
        skuname            = sku)

    nictemplate = AzManagers.build_nictemplate(
        TEMPLATE_NAME;
        accelerated        = false,
        subscriptionid     = subscriptionid,
        location           = location,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet)

    AzManagers.save_template_scaleset(TEMPLATE_NAME, sstemplate)
    AzManagers.save_template_nic(TEMPLATE_NAME, nictemplate)

    AzSessions.write_manifest(;
        client_id     = client_id,
        client_secret = client_secret,
        tenant        = tenant_id)
    AzManagers.write_manifest(;
        resourcegroup  = resourcegroup,
        subscriptionid = subscriptionid,
        ssh_user       = ssh_user)

    AzSession(; protocal = AzClientCredentials)
end

function log_section(title)
    bar = "=" ^ 70
    @info bar
    @info title
    @info bar
end

"""
Probe one worker for the SKU's machine topology and log it. Gives a
clear reference point for what placement is being computed against,
before any per-worker placement is dumped.
"""
function dump_machine_topology()
    log_section("Machine topology (as seen by worker $(first(workers())))")
    topo = remotecall_fetch(first(workers())) do
        try
            t = AzManagers.detect_machine_topology()
            (
                ok = true,
                physical_cores = t.physical_cores,
                logical_cpus   = length(t.logical_cpus),
                hyperthreading = t.hyperthreading,
                sockets        = length(t.sockets),
                numa_nodes     = length(t.numa_nodes),
                socket_cpus    = [(s.id, length(s.cpu_set)) for s in t.sockets],
                numa_cpus      = [(n.id, n.socket, length(n.cpu_set)) for n in t.numa_nodes],
            )
        catch e
            (ok = false, error = sprint(showerror, e))
        end
    end
    if !topo.ok
        @warn "detect_machine_topology failed on worker" error=topo.error
        return
    end
    @info("topology",
          physical_cores = topo.physical_cores,
          logical_cpus   = topo.logical_cpus,
          hyperthreading = topo.hyperthreading,
          sockets        = topo.sockets,
          numa_nodes     = topo.numa_nodes)
    for (sid, ncpu) in topo.socket_cpus
        @info "  socket $sid: $ncpu logical CPUs"
    end
    for (nid, sid, ncpu) in topo.numa_cpus
        @info "  numa $nid (socket $sid): $ncpu logical CPUs"
    end
end

function dump_worker_placements()
    log_section("Per-worker placement (planner output, recorded at handshake)")
    placements = worker_placements()
    for pid in sort(collect(keys(placements)))
        info = placements[pid]
        hostname = try
            remotecall_fetch(gethostname, pid)
        catch
            "<unreachable>"
        end
        # `@info(msg, k=v...)` produces a multi-line log entry with each
        # key on its own line - much easier to scan in CI than the single
        # "k=v k=v k=v" form.
        @info("worker pid=$pid",
              hostname        = hostname,
              localid         = get(info, "localid", "?"),
              cpu_set         = get(info, "cpu_set", "?"),
              numa_node       = get(info, "numa_node", "?"),
              socket          = get(info, "socket", "?"),
              julia_threads   = get(info, "julia_threads", "?"),
              pinning_backend = get(info, "pinning_backend", "?"),
              physical_cores  = get(info, "physical_cores", "?"),
              omp_threads     = get(info, "omp_threads", "?"))
    end
    placements
end

function check_taskset_matches(placements)
    log_section("taskset affinity check (kernel-observed vs planner expected)")
    for pid in workers()
        info = get(placements, pid, Dict())
        expected = get(info, "cpu_set", "")
        affinity = remotecall_fetch(pid) do
            try
                strip(read(`taskset -pc $(getpid())`, String))
            catch e
                "taskset failed: $e"
            end
        end
        # taskset's `affinity` line is "pid <N>'s current affinity list: <range>"
        # - check that the expected range is in there. Empty expected is
        # the ppi=1 path where no cpu_set was planned; nothing to check.
        if isempty(expected)
            @info "pid $pid: no cpu_set planned (ppi=1 path); skipping affinity check" taskset=affinity
        else
            match = occursin(expected, affinity)
            if match
                @info "pid $pid: PASS" expected=expected taskset=affinity
            else
                @warn "pid $pid: FAIL - expected '$expected' not present in affinity" expected=expected taskset=affinity
            end
            @test match
        end
    end
end

"""
Print a per-worker side-by-side comparison of what each worker is bound
to (cpu_set, NUMA, socket) so you can eyeball whether the distribution
makes sense for the SKU and ppi.
"""
function dump_distribution_summary(placements)
    log_section("Placement distribution summary")
    cpu_sets  = unique(get(p, "cpu_set",   "")       for p in values(placements))
    numas     = unique(get(p, "numa_node", nothing)  for p in values(placements))
    sockets   = unique(get(p, "socket",    nothing)  for p in values(placements))
    @info("distinct counts across workers",
          workers        = length(placements),
          unique_cpu_sets = length(cpu_sets),
          unique_numa    = length(numas),
          unique_sockets = length(sockets),
          numa_values    = sort(collect(numas);    by = x -> something(x, -1)),
          socket_values  = sort(collect(sockets);  by = x -> something(x, -1)),
          cpu_sets       = sort(collect(cpu_sets)))
end

"""
Parse a cpu_set range string (e.g. "0-29,60-89") into a Set{Int} of
individual CPU IDs. Used by check_omp_pinning to compare per-OMP-thread
affinities against the worker's planned cpu_set.
"""
function parse_cpu_set_string(s::AbstractString)
    cpus = Set{Int}()
    for part in split(s, ",")
        part = strip(part)
        isempty(part) && continue
        if '-' in part
            lo, hi = parse.(Int, split(part, "-"; limit=2))
            union!(cpus, lo:hi)
        else
            push!(cpus, parse(Int, part))
        end
    end
    cpus
end

const OMP_AFFINITY_SRC = """
#define _GNU_SOURCE
#include <stdio.h>
#include <sched.h>
#include <omp.h>

int main() {
    #pragma omp parallel
    {
        int tid = omp_get_thread_num();
        int nt  = omp_get_num_threads();
        cpu_set_t mask;
        CPU_ZERO(&mask);
        sched_getaffinity(0, sizeof(mask), &mask);

        #pragma omp critical
        {
            printf("thread %d/%d cpus:", tid, nt);
            for (int i = 0; i < CPU_SETSIZE; i++) {
                if (CPU_ISSET(i, &mask)) printf(" %d", i);
            }
            printf("\\n");
        }
    }
    return 0;
}
"""

"""
Compile and run a tiny OpenMP program on each worker to verify that OMP
threads are actually pinned to the worker's planned cpu_set. The
placement planner sets `OMP_NUM_THREADS`, `OMP_PROC_BIND=close`, and
`OMP_PLACES=cores` in each worker's environment; this function checks
that those settings are effective by reading the kernel-level per-thread
affinity mask via `sched_getaffinity`.

The check runs three configurations per worker to cover both the normal
and edge cases:
  - default:  OMP_NUM_THREADS = omp_threads (= physical cores in cpu_set)
  - subset:   OMP_NUM_THREADS = half the default (fewer threads than cores)
  - oversub:  OMP_NUM_THREADS = double the default (more threads than cores)
In ALL cases the assertion is the same: every OMP thread must run on
CPUs within the worker's planned cpu_set. Oversubscription is valid
(threads time-share cores) as long as affinity doesn't escape the set.

Requires `gcc` on the worker (installed in the base image).
"""
function check_omp_pinning(placements)
    log_section("OpenMP thread affinity check")
    for pid in sort(collect(keys(placements)))
        info = placements[pid]
        expected_cpu_str = get(info, "cpu_set", "")
        isempty(expected_cpu_str) && continue
        expected_cpus = parse_cpu_set_string(expected_cpu_str)
        default_omp   = get(info, "omp_threads", length(expected_cpus))
        default_omp < 1 && (default_omp = length(expected_cpus))

        # Compile once on the worker
        try
            remotecall_fetch(pid, OMP_AFFINITY_SRC) do src
                write("/tmp/omp_affinity_test.c", src)
                run(`gcc -fopenmp -o /tmp/omp_affinity_test /tmp/omp_affinity_test.c`)
            end
        catch e
            @warn "pid $pid: OMP compile failed (gcc missing?)" exception=e
            @test false
            continue
        end

        # Run with multiple OMP_NUM_THREADS values
        cases = [
            ("default",        default_omp),
            ("half (subset)",  max(1, div(default_omp, 2))),
            ("double (oversub)", 2 * default_omp),
        ]
        # De-dup (e.g., default_omp=1 makes half=1, same case)
        seen = Set{Int}()
        unique_cases = Tuple{String,Int}[]
        for (label, nt) in cases
            nt in seen && continue
            push!(seen, nt)
            push!(unique_cases, (label, nt))
        end

        for (label, nthreads) in unique_cases
            output = try
                remotecall_fetch(pid, nthreads) do nt
                    withenv("OMP_NUM_THREADS" => string(nt)) do
                        strip(read(`/tmp/omp_affinity_test`, String))
                    end
                end
            catch e
                @warn "pid $pid OMP_NUM_THREADS=$nthreads ($label): run failed" exception=e
                @test false
                continue
            end

            all_inside = true
            n_threads_seen = 0
            for line in split(output, "\n")
                m = match(r"thread (\d+)/(\d+) cpus:(.*)", line)
                m === nothing && continue
                n_threads_seen += 1
                thread_cpus = Set(parse.(Int, split(strip(m.captures[3]))))
                outside = setdiff(thread_cpus, expected_cpus)
                if !isempty(outside)
                    @warn "pid $pid thread $(m.captures[1]) ($label): CPUs $outside outside cpu_set=$expected_cpu_str"
                    all_inside = false
                end
            end

            if all_inside
                @info "pid $pid OMP_NUM_THREADS=$nthreads ($label): PASS ($n_threads_seen threads, all within $expected_cpu_str)"
            else
                @warn "pid $pid OMP_NUM_THREADS=$nthreads ($label): FAIL"
            end
            @test all_inside
            @test n_threads_seen == nthreads
        end
    end
end

function teardown(cfg, group, session)
    if get_bool(cfg, :scenarios, :keep)
        @warn "scenarios.keep=true; leaving workers + scale set '$group' running"
        return
    end
    @info "teardown: starting" group nworkers=nworkers()
    if !isempty(workers())
        try
            # Bound the wait. rmprocs default is `waitfor=typemax(Int)` -
            # if a worker doesn't respond to kill the CI shard hangs
            # silently forever (until the GHA job timeout cancels it).
            t0 = time()
            rmprocs(workers(); waitfor=120)
            @info "teardown: rmprocs done" elapsed_s=round(time()-t0; digits=1)
        catch e
            @warn "teardown: rmprocs failed/timed out" exception=e
        end
    end
    try
        t0 = time()
        # `rmgroup` defaults to `session=AzSession(;lazy=true)` which on
        # first token() falls through to device-code flow - hangs the
        # CI shard for 15 minutes then errors expired_token. Pass the
        # service-principal session explicitly.
        AzManagers.rmgroup(group; session=session)
        @info "teardown: rmgroup done" elapsed_s=round(time()-t0; digits=1)
    catch e
        @warn "rmgroup($group) failed; check scale set manually" exception=e
    end
    @info "teardown complete for scale set $group"
end

function run_basic_scenario(cfg, session)
    group = "mwt-basic-" * randstring('a':'z',8)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    log_section("Basic scenario: ppi=1, n=1, spot=$spot, group=$group")
    @info "calling addprocs..."
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = 1,
        spot    = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()
    try
        @testset "basic scenario" begin
            @test nworkers() == 1
            pid = first(workers())
            hostname = remotecall_fetch(gethostname, pid)
            @info "worker pid=$pid hostname=$hostname"
        end
    finally
        teardown(cfg, group, session)
    end
end

"""
Sweep through a matrix of ppi values derived from the SKU's own topology
and verify, per worker, that:
  - the recorded placement (cpu_set, numa_node, socket) matches what
    `AzManagers.plan_worker_placements(topology, ppi)` computed on the
    driver
  - the kernel-level affinity (`taskset -pc`) matches the recorded
    cpu_set

No expected counts are hardcoded anywhere; everything is derived from
the topology the SKU itself reports at runtime. The matrix is:

  ppi = 1            (smoke test, also doubles as topology probe)
  ppi = sockets       (1 worker per socket)
  ppi = numa_nodes    (1 worker per NUMA - skipped if same as sockets)
  ppi = 2 * numa_nodes (2 workers per NUMA - exercises the sub-NUMA
                        slicing path)

Each case provisions its own scale-set; teardown happens in `finally`.
"""
function run_pinning_matrix_scenario(cfg, session)
    sku  = get_field(cfg, :azure, :sku_name; default = "?")
    spot = get_bool(cfg, :azure, :spot;     default = true)
    log_section("Pinning matrix scenario: SKU=$sku spot=$spot")

    # ppi=1 probe + smoke, then sockets / numa / 2*numa.
    topology = run_pinning_case_ppi1(cfg, session)
    topology === nothing && return

    n_socket = length(topology.sockets)
    n_numa   = length(topology.numa_nodes)

    cases = Tuple{String,Int}[]
    push!(cases, ("ppi=$n_socket (1 worker per socket)", n_socket))
    if n_numa != n_socket
        push!(cases, ("ppi=$n_numa (1 worker per NUMA)", n_numa))
    end
    push!(cases, ("ppi=$(2 * n_numa) (2 workers per NUMA)", 2 * n_numa))

    seen = Set([1])
    for (label, ppi) in cases
        ppi in seen && continue
        push!(seen, ppi)
        run_pinning_case(cfg, session, topology, label, ppi)
    end
end

"""
ppi=1 case: smoke test + topology probe. The primary worker on each VM
is launched by cloud-init without numactl, and for ppi=1 no additional
workers are spawned, so `worker_placement_metadata` is never merged into
the worker's userdata. We assert connectivity only and use the worker to
probe topology for the subsequent matrix cases.
"""
function run_pinning_case_ppi1(cfg, session)
    log_section("ppi=1 (smoke + topology probe)")
    group = "mwt-" * randstring('a':'z',8)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    @info "calling addprocs..." group=group ppi=1 spot=spot
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = 1,
        spot    = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()

    topology = nothing
    try
        @testset "ppi=1 (smoke + probe)" begin
            @test nworkers() == 1
            pid = first(workers())
            hostname = remotecall_fetch(gethostname, pid)
            @info "worker pid=$pid hostname=$hostname"

            topology = remotecall_fetch(pid) do
                AzManagers.detect_machine_topology()
            end
            log_section("Detected SKU topology")
            @info "topology" physical_cores=topology.physical_cores logical_cpus=length(topology.logical_cpus) hyperthreading=topology.hyperthreading sockets=length(topology.sockets) numa_nodes=length(topology.numa_nodes)
            for s in topology.sockets
                @info "  socket $(s.id): $(length(s.cpu_set)) logical CPUs"
            end
            for n in topology.numa_nodes
                @info "  numa $(n.id) (socket $(n.socket)): $(length(n.cpu_set)) logical CPUs"
            end
        end
    finally
        teardown(cfg, group, session)
    end
    topology
end

"""
One ppi case in the matrix. Computes the expected placement plan locally
on the driver via `plan_worker_placements(topology, ppi)`, then provisions
a scale-set, then for each worker (matched to expected by `localid`)
asserts:
  - observed `cpu_set` (recorded in worker userdata) == expected
  - kernel `taskset -pc` affinity contains the expected cpu_set range
"""
function run_pinning_case(cfg, session, topology, label, ppi)
    log_section("$label")
    group = "mwt-" * randstring('a':'z',8)
    spot  = get_bool(cfg, :azure, :spot; default = true)

    expected = AzManagers.plan_worker_placements(topology, ppi)
    log_section("Expected placements (AzManagers.plan_worker_placements)")
    for p in expected
        @info "  expected localid=$(p.localid)" cpu_set=AzManagers.cpu_set_string(p.cpu_set) numa_node=p.numa_node socket=p.socket julia_threads=p.julia_threads
    end

    @info "calling addprocs..." group=group ppi=ppi spot=spot
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = ppi,
        spot    = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()

    try
        @testset "$label" begin
            @test nworkers() == ppi

            # Map workers by localid so we can pair each observation with
            # the matching expected placement deterministically.
            localid_to_pid = Dict{Int,Int}()
            for pid in workers()
                lid = get(AzManagers.worker_placement(pid), "localid", 0)
                localid_to_pid[lid] = pid
            end

            for p_expected in expected
                lid = p_expected.localid
                pid = get(localid_to_pid, lid, nothing)
                if pid === nothing
                    @error "no observed worker with localid=$lid" map=localid_to_pid
                    @test false
                    continue
                end

                p_observed   = AzManagers.worker_placement(pid)
                expected_cpu = AzManagers.cpu_set_string(p_expected.cpu_set)
                observed_cpu = get(p_observed, "cpu_set", "")
                affinity = remotecall_fetch(pid) do
                    try
                        strip(read(`taskset -pc $(getpid())`, String))
                    catch e
                        "taskset failed: $e"
                    end
                end

                @info "pid=$pid localid=$lid" expected_cpu=expected_cpu observed_cpu=observed_cpu expected_numa=p_expected.numa_node observed_numa=get(p_observed, "numa_node", "?") expected_socket=p_expected.socket observed_socket=get(p_observed, "socket", "?") taskset=affinity

                # Property 1: recorded cpu_set matches what the planner
                # computed on the driver (verifies the placement flowed
                # through addprocs → worker_placement_metadata correctly).
                @test observed_cpu == expected_cpu

                # Property 2: kernel-level affinity actually enforces the
                # recorded cpu_set (verifies numactl on additional workers
                # and the primary self-pin via taskset).
                @test occursin(observed_cpu, affinity)
            end

            # Property 3: OpenMP threads spawned by a C program on each
            # worker are actually bound to CPUs within the worker's
            # planned cpu_set (verifies OMP_NUM_THREADS / OMP_PROC_BIND
            # / OMP_PLACES are effective, not just set in ENV).
            observed_placements = Dict(pid => AzManagers.worker_placement(pid) for pid in workers())
            check_omp_pinning(observed_placements)
        end
    finally
        teardown(cfg, group, session)
    end
end

function run_mpi_nested_scenario(cfg, session)
    group                = "mwt-mpi-" * randstring('a':'z',8)
    ppi                  = get_int(cfg, :scenarios, :ppi; default = 2)
    mpi_ranks_per_worker = get_int(cfg, :scenarios, :mpi_ranks_per_worker; default = 2)
    spot                 = get_bool(cfg, :azure, :spot; default = true)
    sku                  = get_field(cfg, :azure, :sku_name; default = "?")
    # mpi_flags defaults to "" so the auto-emitted `--bind-to cpu-list:ordered`
    # is not overridden. Set scenarios.mpi_flags in the TOML if your image
    # needs extra mpirun flags.
    mpi_flags = string(get_field(cfg, :scenarios, :mpi_flags; default = "", required = false))

    log_section("MPI-nested scenario: SKU=$sku ppi=$ppi ranks/worker=$mpi_ranks_per_worker spot=$spot")
    @info("expected",
          julia_workers       = ppi,
          mpi_ranks_per_worker = mpi_ranks_per_worker,
          total_mpi_ranks      = ppi * mpi_ranks_per_worker,
          mpi_flags            = mpi_flags)
    @info "calling addprocs..." group=group
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor              = true,
        ppi                  = ppi,
        mpi_ranks_per_worker = mpi_ranks_per_worker,
        mpi_flags            = mpi_flags,
        spot                 = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()
    try
        @testset "MPI nested scenario (ppi=$ppi, ranks/worker=$mpi_ranks_per_worker)" begin
            @test nworkers() == ppi
            log_section("MPI rank introspection (one MPI.Comm_size call per worker)")
            for pid in workers()
                hostname = try; remotecall_fetch(gethostname, pid); catch; "<unreachable>"; end
                rank_count = remotecall_fetch(pid) do
                    try
                        Base.invokelatest(eval, :(using MPI; MPI.Comm_size(MPI.COMM_WORLD)))
                    catch e
                        "MPI introspection failed: $e"
                    end
                end
                if rank_count == mpi_ranks_per_worker
                    @info "pid $pid: PASS" hostname=hostname expected=mpi_ranks_per_worker got=rank_count
                else
                    @warn "pid $pid: FAIL" hostname=hostname expected=mpi_ranks_per_worker got=rank_count
                end
                @test rank_count == mpi_ranks_per_worker
            end
            dump_machine_topology()
            placements = dump_worker_placements()
            dump_distribution_summary(placements)
        end
    finally
        teardown(cfg, group, session)
    end
end

function main()
    if !isempty(ARGS) && ARGS[1] == "--init"
        path = length(ARGS) >= 2 ? ARGS[2] : DEFAULT_CONFIG_PATH
        init_config(path)
        return
    end

    config_path = isempty(ARGS) ? DEFAULT_CONFIG_PATH : ARGS[1]
    cfg = load_config(config_path)
    @info "loaded config from $config_path"

    session = build_test_templates(cfg)

    any_run = false
    if get_bool(cfg, :scenarios, :basic);      any_run = true; run_basic_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :placement);  any_run = true; run_pinning_matrix_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :mpi_nested); any_run = true; run_mpi_nested_scenario(cfg, session); end
    any_run || @warn "no scenario enabled in $config_path; flip [scenarios] entries to true"
end

main()
