name: Unit Tests
on: [push, pull_request]
jobs:
  AzManagers:
    strategy:
      matrix:
        julia-version: [1.5] #1.0
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      TENANT_ID: "${{ secrets.TENANT_ID }}" 
      SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      LOCATION: "eastus2"
      RESOURCE_GROUP: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}"
      CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      GALLERY_NAME: "${{ github.run_id }}${{ matrix.julia-version }}gallery"
      IMAGE_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-image"
      IMAGE_DEFINITION_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-image-definition"
      IMAGE_BUILDER_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-image-builder"
      VM_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-vm"
      PUBLIC_IP_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-pubip"
      VNET_NAME: "${{ matrix.os }}-${{ matrix.julia-version }}-${{ github.run_id }}-vnet"
      SUBNET_NAME: "default"
      IDENTITY_NAME: "${{ matrix.os }}-${{ github.run_id }}-identity"
      COMMIT_SHA: "${{ github.sha }}"
      JULIA_VERSION: "${{ matrix.julia-version }}"

    steps:
      - name: Checkout the AzManagers Repo
        uses: actions/checkout@v1.0.0

      - name: Create an SSH Key Pair on the GitHub Actions Runner
        run: ssh-keygen -f /home/runner/.ssh/azmanagers_rsa -N ''

      - name: Login to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group, Shared Image Gallery, Image Definition, VNet and Subnet
        run: |
          az group create                 -g "$RESOURCE_GROUP" -l "$LOCATION"
          az group wait                   -g "$RESOURCE_GROUP" --created 
          az sig create                   -g "$RESOURCE_GROUP" -r "$GALLERY_NAME"
          az sig image-definition create  -g "$RESOURCE_GROUP" -r "$GALLERY_NAME" -i "$IMAGE_DEFINITION_NAME" -p "canonical" -f "0001-com-ubuntu-server-focal" -s "20_04-lts" --os-type linux
          az network vnet create          -g "$RESOURCE_GROUP" -n "$VNET_NAME" --subnet-name "$SUBNET_NAME"
          az identity create              -g "$RESOURCE_GROUP" -n "$IDENTITY_NAME"
          ID_CLIENT_ID=$(az identity show -g "$RESOURCE_GROUP" -n "$IDENTITY_NAME" | jq '.principalId' | cut -d "\"" -f 2)
          sleep 1m
          az role assignment create --assignee-object-id "$ID_CLIENT_ID" --role "Contributor" --scope "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP"
        # az image builder create         -g "$RESOURCE_GROUP" -n "$IMAGE_BUILDER_NAME" --shared-image-destinations "$GALLERY_NAME/$IMAGE_DEFINITION_NAME=$LOCATION" --managed-image-destinations "$IMAGE_NAME=$LOCATION" --image-source "Canonical:UbuntuServer:18.04-LTS:latest" --identity "$IDENTITY_NAME"

      # - name: Template the Packer Image file
      #   uses: cuchi/jinja2-action@v1.2.0
      #   with:
      #     template: /home/runner/work/AzManagers.jl/AzManagers.jl/templates/cofii-base.json.j2
      #     output_file: /home/runner/work/AzManagers.jl/AzManagers.jl/templates/cofii-base.json

      - name: Template the AzManagers Setup script
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: /home/runner/work/AzManagers.jl/AzManagers.jl/templates/azmanagers-setup.jl.j2
          output_file: /home/runner/work/AzManagers.jl/AzManagers.jl/templates/azmanagers-setup.jl

      - name: BUILD-CUSTOM-VM-IMAGE      
        uses: azure/build-vm-image@v0
        with:        
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          managed-identity: ${{ env.IDENTITY_NAME }}
          location: ${{ env.LOCATION }}
          vm-size: "Standard_D8s_v3"
          source-os-type: "linux"        
          source-image-type: "PlatformImage"
          source-image: Canonical:UbuntuServer:18.04-LTS:latest 
          dist-type: "SharedImageGallery"
          dist-resource-id: "/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.Compute/galleries/${{ env.GALLERY_NAME }}/images/${{ env.IMAGE_DEFINITION_NAME }}"
          dist-location: ${{ env.LOCATION }}


      # # - name: Install Packer
      # #   run: |
      # #     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      # #     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      # #     sudo apt-get update && sudo apt-get install packer

      # # - name: Build the Packer Image
      # #   run: packer build -color=false -timestamp-ui /home/runner/work/AzManagers.jl/AzManagers.jl/templates/cofii-base.json

      # - name: Create the Master VM
      #   run: az vm create -g "$RESOURCE_GROUP" -n "$VM_NAME" --image "UbuntuLTS" --public-ip-address "$PUBLIC_IP_NAME" --subnet "$SUBNET_NAME" --vnet-name "$VNET_NAME" --ssh-key-values @/home/runner/.ssh/azmanagers_rsa.pub @/home/runner/work/AzManagers.jl/AzManagers.jl/mcpu-key.pub --admin-username cvx

      # # could use detach functionality from AzManagers in place of ssh here
      # - name: Run the Unit Tests on the Master VM
      #   run: |
      #     echo "Grabbing the Master VM's Pubic IP Address..."
      #     ipaddress=$(az network public-ip show -g "$RESOURCE_GROUP" -n "$PUBLIC_IP_NAME" | jq '.ipAddress' | cut -d "\"" -f 2)
          
      #     echo "scp-ing the Runner ssh keys and the coverage script to the Master VM..."
      #     scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa /home/runner/.ssh/azmanagers_rsa.pub cvx@$ipaddress:/home/cvx/.ssh/azmanagers_rsa.pub
      #     scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa /home/runner/.ssh/azmanagers_rsa cvx@$ipaddress:/home/cvx/.ssh/azmanagers_rsa
      #     scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa /home/runner/work/AzManagers.jl/AzManagers.jl/test/julia-codecov.jl cvx@$ipaddress:/home/cvx/julia-codecov.jl
      #     scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa /home/runner/work/AzManagers.jl/AzManagers.jl/templates/cofii-base.json cvx@$ipaddress:/home/cvx/cofii-base.json
      #     scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa /home/runner/work/AzManagers.jl/AzManagers.jl/templates/azmanagers-setup.jl cvx@$ipaddress:/home/cvx/azmanagers-setup.jl
          
      #   # echo "Running the Unit Tests..."
      #   # ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa cvx@$ipaddress "julia --code-coverage=user -e 'using Pkg; Pkg.test(\"AzManagers\"; coverage=true)'"

      #   # echo "Running the Code Coverage Script..."
      #   # ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa cvx@$ipaddress "julia -e 'include(\"/home/cvx/julia-codecov.jl\")'"

      #   # echo "Grabbing and scp-ing the Coverage Report path..."
      #   # lcovpath=$(ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa cvx@$ipaddress "find -name lcov.info")
      #   # scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/azmanagers_rsa cvx@$ipaddress:$lcovpath /home/runner/lcov.info

      # # - name: Upload the Code Coverage Report to Codecov
      # #   uses: codecov/codecov-action@v1
      # #   with:
      # #     file: /home/runner/lcov.info

      - name: Delete the Resource Group
        run: |
          az group delete -g "$RESOURCE_GROUP" --yes
        if: ${{ always() }}
