name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0, 1.5]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest #change lastest to master
      - uses: julia-actions/julia-runtest@latest #change lastest to master
        env:
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          resource_group: ${{ secrets.RESOURCE_GROUP_NAME }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info


# jobs:
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         julia-version: [1.0, 1.5]
#         os: [ubuntu-latest]
#     steps:
#       - uses: actions/checkout@v1.0.0
#       - uses: julia-actions/setup-julia@latest
#         with:
#           version: ${{ matrix.julia-version }}
#       - uses: julia-actions/julia-buildpkg@master
#       - uses: julia-actions/julia-runtest@master
#       - uses: julia-actions/julia-processcoverage@v1
#       - uses: codecov/codecov-action@v1
#         with:
#           file: lcov.info